-- PRIMARY KEY, indexes created AFTER COPY to speed up parallel load (TPC-H style).
-- Order: PRIMARY KEY first, then indexes.

-- Primary keys
ALTER TABLE tpcds.call_center ADD PRIMARY KEY (cc_call_center_sk);
ALTER TABLE tpcds.catalog_page ADD PRIMARY KEY (cp_catalog_page_sk);
ALTER TABLE tpcds.catalog_returns ADD PRIMARY KEY (cr_item_sk, cr_order_number);
ALTER TABLE tpcds.catalog_sales ADD PRIMARY KEY (cs_item_sk, cs_order_number);
ALTER TABLE tpcds.customer ADD PRIMARY KEY (c_customer_sk);
ALTER TABLE tpcds.customer_address ADD PRIMARY KEY (ca_address_sk);
ALTER TABLE tpcds.customer_demographics ADD PRIMARY KEY (cd_demo_sk);
ALTER TABLE tpcds.date_dim ADD PRIMARY KEY (d_date_sk);
ALTER TABLE tpcds.household_demographics ADD PRIMARY KEY (hd_demo_sk);
ALTER TABLE tpcds.income_band ADD PRIMARY KEY (ib_income_band_sk);
ALTER TABLE tpcds.inventory ADD PRIMARY KEY (inv_date_sk, inv_item_sk, inv_warehouse_sk);
ALTER TABLE tpcds.item ADD PRIMARY KEY (i_item_sk);
ALTER TABLE tpcds.promotion ADD PRIMARY KEY (p_promo_sk);
ALTER TABLE tpcds.reason ADD PRIMARY KEY (r_reason_sk);
ALTER TABLE tpcds.ship_mode ADD PRIMARY KEY (sm_ship_mode_sk);
ALTER TABLE tpcds.store ADD PRIMARY KEY (s_store_sk);
ALTER TABLE tpcds.store_returns ADD PRIMARY KEY (sr_item_sk, sr_ticket_number);
ALTER TABLE tpcds.store_sales ADD PRIMARY KEY (ss_item_sk, ss_ticket_number);
ALTER TABLE tpcds.time_dim ADD PRIMARY KEY (t_time_sk);
ALTER TABLE tpcds.warehouse ADD PRIMARY KEY (w_warehouse_sk);
ALTER TABLE tpcds.web_page ADD PRIMARY KEY (wp_web_page_sk);
ALTER TABLE tpcds.web_returns ADD PRIMARY KEY (wr_order_number, wr_item_sk);
ALTER TABLE tpcds.web_sales ADD PRIMARY KEY (ws_item_sk, ws_order_number);
ALTER TABLE tpcds.web_site ADD PRIMARY KEY (web_site_sk);

-- Indexes (from former 051.postgresql.foreignkeys.sql + 052.postgresql.indexes.sql)
CREATE INDEX idx_ss_sold_date_sk ON tpcds.store_sales (ss_sold_date_sk);
CREATE INDEX idx_ss_sold_time_sk ON tpcds.store_sales (ss_sold_time_sk);
CREATE INDEX idx_ss_item_sk ON tpcds.store_sales (ss_item_sk);
CREATE INDEX idx_ss_customer_sk ON tpcds.store_sales (ss_customer_sk);
CREATE INDEX idx_ss_cdemo_sk ON tpcds.store_sales (ss_cdemo_sk);
CREATE INDEX idx_ss_hdemo_sk ON tpcds.store_sales (ss_hdemo_sk);
CREATE INDEX idx_ss_addr_sk ON tpcds.store_sales (ss_addr_sk);
CREATE INDEX idx_ss_store_sk ON tpcds.store_sales (ss_store_sk);
CREATE INDEX idx_ss_promo_sk ON tpcds.store_sales (ss_promo_sk);
CREATE INDEX idx_ss_ticket_number ON tpcds.store_sales (ss_ticket_number);
CREATE INDEX idx_sr_returned_date_sk ON tpcds.store_returns (sr_returned_date_sk);
CREATE INDEX idx_sr_return_time_sk ON tpcds.store_returns (sr_return_time_sk);
CREATE INDEX idx_sr_item_sk ON tpcds.store_returns (sr_item_sk);
CREATE INDEX idx_sr_customer_sk ON tpcds.store_returns (sr_customer_sk);
CREATE INDEX idx_sr_cdemo_sk ON tpcds.store_returns (sr_cdemo_sk);
CREATE INDEX idx_sr_hdemo_sk ON tpcds.store_returns (sr_hdemo_sk);
CREATE INDEX idx_sr_addr_sk ON tpcds.store_returns (sr_addr_sk);
CREATE INDEX idx_sr_store_sk ON tpcds.store_returns (sr_store_sk);
CREATE INDEX idx_sr_reason_sk ON tpcds.store_returns (sr_reason_sk);
CREATE INDEX idx_sr_ticket_number ON tpcds.store_returns (sr_ticket_number);
CREATE INDEX idx_cs_sold_date_sk ON tpcds.catalog_sales (cs_sold_date_sk);
CREATE INDEX idx_cs_sold_time_sk ON tpcds.catalog_sales (cs_sold_time_sk);
CREATE INDEX idx_cs_ship_date_sk ON tpcds.catalog_sales (cs_ship_date_sk);
CREATE INDEX idx_cs_bill_customer_sk ON tpcds.catalog_sales (cs_bill_customer_sk);
CREATE INDEX idx_cs_bill_cdemo_sk ON tpcds.catalog_sales (cs_bill_cdemo_sk);
CREATE INDEX idx_cs_bill_hdemo_sk ON tpcds.catalog_sales (cs_bill_hdemo_sk);
CREATE INDEX idx_cs_bill_addr_sk ON tpcds.catalog_sales (cs_bill_addr_sk);
CREATE INDEX idx_cs_ship_customer_sk ON tpcds.catalog_sales (cs_ship_customer_sk);
CREATE INDEX idx_cs_ship_cdemo_sk ON tpcds.catalog_sales (cs_ship_cdemo_sk);
CREATE INDEX idx_cs_ship_hdemo_sk ON tpcds.catalog_sales (cs_ship_hdemo_sk);
CREATE INDEX idx_cs_ship_addr_sk ON tpcds.catalog_sales (cs_ship_addr_sk);
CREATE INDEX idx_cs_call_center_sk ON tpcds.catalog_sales (cs_call_center_sk);
CREATE INDEX idx_cs_catalog_page_sk ON tpcds.catalog_sales (cs_catalog_page_sk);
CREATE INDEX idx_cs_ship_mode_sk ON tpcds.catalog_sales (cs_ship_mode_sk);
CREATE INDEX idx_cs_warehouse_sk ON tpcds.catalog_sales (cs_warehouse_sk);
CREATE INDEX idx_cs_item_sk ON tpcds.catalog_sales (cs_item_sk);
CREATE INDEX idx_cs_promo_sk ON tpcds.catalog_sales (cs_promo_sk);
CREATE INDEX idx_cs_order_number ON tpcds.catalog_sales (cs_order_number);
CREATE INDEX idx_cr_returned_date_sk ON tpcds.catalog_returns (cr_returned_date_sk);
CREATE INDEX idx_cr_returned_time_sk ON tpcds.catalog_returns (cr_returned_time_sk);
CREATE INDEX idx_cr_item_sk ON tpcds.catalog_returns (cr_item_sk);
CREATE INDEX idx_cr_refunded_customer_sk ON tpcds.catalog_returns (cr_refunded_customer_sk);
CREATE INDEX idx_cr_refunded_cdemo_sk ON tpcds.catalog_returns (cr_refunded_cdemo_sk);
CREATE INDEX idx_cr_refunded_hdemo_sk ON tpcds.catalog_returns (cr_refunded_hdemo_sk);
CREATE INDEX idx_cr_refunded_addr_sk ON tpcds.catalog_returns (cr_refunded_addr_sk);
CREATE INDEX idx_cr_returning_customer_sk ON tpcds.catalog_returns (cr_returning_customer_sk);
CREATE INDEX idx_cr_returning_cdemo_sk ON tpcds.catalog_returns (cr_returning_cdemo_sk);
CREATE INDEX idx_cr_returning_hdemo_sk ON tpcds.catalog_returns (cr_returning_hdemo_sk);
CREATE INDEX idx_cr_returning_addr_sk ON tpcds.catalog_returns (cr_returning_addr_sk);
CREATE INDEX idx_cr_call_center_sk ON tpcds.catalog_returns (cr_call_center_sk);
CREATE INDEX idx_cr_catalog_page_sk ON tpcds.catalog_returns (cr_catalog_page_sk);
CREATE INDEX idx_cr_ship_mode_sk ON tpcds.catalog_returns (cr_ship_mode_sk);
CREATE INDEX idx_cr_warehouse_sk ON tpcds.catalog_returns (cr_warehouse_sk);
CREATE INDEX idx_cr_reason_sk ON tpcds.catalog_returns (cr_reason_sk);
CREATE INDEX idx_cr_order_number ON tpcds.catalog_returns (cr_order_number);
CREATE INDEX idx_ws_sold_date_sk ON tpcds.web_sales (ws_sold_date_sk);
CREATE INDEX idx_ws_sold_time_sk ON tpcds.web_sales (ws_sold_time_sk);
CREATE INDEX idx_ws_ship_date_sk ON tpcds.web_sales (ws_ship_date_sk);
CREATE INDEX idx_ws_item_sk ON tpcds.web_sales (ws_item_sk);
CREATE INDEX idx_ws_bill_customer_sk ON tpcds.web_sales (ws_bill_customer_sk);
CREATE INDEX idx_ws_bill_cdemo_sk ON tpcds.web_sales (ws_bill_cdemo_sk);
CREATE INDEX idx_ws_bill_hdemo_sk ON tpcds.web_sales (ws_bill_hdemo_sk);
CREATE INDEX idx_ws_bill_addr_sk ON tpcds.web_sales (ws_bill_addr_sk);
CREATE INDEX idx_ws_ship_customer_sk ON tpcds.web_sales (ws_ship_customer_sk);
CREATE INDEX idx_ws_ship_cdemo_sk ON tpcds.web_sales (ws_ship_cdemo_sk);
CREATE INDEX idx_ws_ship_hdemo_sk ON tpcds.web_sales (ws_ship_hdemo_sk);
CREATE INDEX idx_ws_ship_addr_sk ON tpcds.web_sales (ws_ship_addr_sk);
CREATE INDEX idx_ws_web_page_sk ON tpcds.web_sales (ws_web_page_sk);
CREATE INDEX idx_ws_web_site_sk ON tpcds.web_sales (ws_web_site_sk);
CREATE INDEX idx_ws_ship_mode_sk ON tpcds.web_sales (ws_ship_mode_sk);
CREATE INDEX idx_ws_warehouse_sk ON tpcds.web_sales (ws_warehouse_sk);
CREATE INDEX idx_ws_promo_sk ON tpcds.web_sales (ws_promo_sk);
CREATE INDEX idx_ws_order_number ON tpcds.web_sales (ws_order_number);
CREATE INDEX idx_wr_returned_date_sk ON tpcds.web_returns (wr_returned_date_sk);
CREATE INDEX idx_wr_returned_time_sk ON tpcds.web_returns (wr_returned_time_sk);
CREATE INDEX idx_wr_item_sk ON tpcds.web_returns (wr_item_sk);
CREATE INDEX idx_wr_refunded_customer_sk ON tpcds.web_returns (wr_refunded_customer_sk);
CREATE INDEX idx_wr_refunded_cdemo_sk ON tpcds.web_returns (wr_refunded_cdemo_sk);
CREATE INDEX idx_wr_refunded_hdemo_sk ON tpcds.web_returns (wr_refunded_hdemo_sk);
CREATE INDEX idx_wr_refunded_addr_sk ON tpcds.web_returns (wr_refunded_addr_sk);
CREATE INDEX idx_wr_returning_customer_sk ON tpcds.web_returns (wr_returning_customer_sk);
CREATE INDEX idx_wr_returning_cdemo_sk ON tpcds.web_returns (wr_returning_cdemo_sk);
CREATE INDEX idx_wr_returning_hdemo_sk ON tpcds.web_returns (wr_returning_hdemo_sk);
CREATE INDEX idx_wr_returning_addr_sk ON tpcds.web_returns (wr_returning_addr_sk);
CREATE INDEX idx_wr_web_page_sk ON tpcds.web_returns (wr_web_page_sk);
CREATE INDEX idx_wr_reason_sk ON tpcds.web_returns (wr_reason_sk);
CREATE INDEX idx_wr_order_number ON tpcds.web_returns (wr_order_number);
CREATE INDEX idx_inv_date_sk ON tpcds.inventory (inv_date_sk );
CREATE INDEX idx_inv_item_sk ON tpcds.inventory (inv_item_sk );
CREATE INDEX idx_inv_warehouse_sk ON tpcds.inventory (inv_warehouse_sk);
CREATE INDEX idx_s_closed_date_sk ON tpcds.store (s_closed_date_sk);
CREATE INDEX idx_cc_closed_date_sk ON tpcds.call_center (cc_closed_date_sk);
CREATE INDEX idx_cc_open_date_sk ON tpcds.call_center (cc_open_date_sk);
CREATE INDEX idx_cp_start_date_sk ON tpcds.catalog_page (cp_start_date_sk);
CREATE INDEX idx_cp_end_date_sk ON tpcds.catalog_page (cp_end_date_sk);
CREATE INDEX idx_web_open_date_sk ON tpcds.web_site (web_open_date_sk);
CREATE INDEX idx_web_close_date_sk ON tpcds.web_site (web_close_date_sk);
CREATE INDEX idx_wp_creation_date_sk ON tpcds.web_page (wp_creation_date_sk);
CREATE INDEX idx_wp_access_date_sk ON tpcds.web_page (wp_access_date_sk);
CREATE INDEX idx_wp_customer_sk ON tpcds.web_page (wp_customer_sk);
CREATE INDEX idx_c_current_cdemo_sk ON tpcds.customer (c_current_cdemo_sk);
CREATE INDEX idx_c_current_hdemo_sk ON tpcds.customer (c_current_hdemo_sk);
CREATE INDEX idx_c_current_addr_sk ON tpcds.customer (c_current_addr_sk);
CREATE INDEX idx_c_first_shipto_date_sk ON tpcds.customer (c_first_shipto_date_sk);
CREATE INDEX idx_c_first_sales_date_sk ON tpcds.customer (c_first_sales_date_sk);
CREATE INDEX idx_hd_income_band_sk ON tpcds.household_demographics (hd_income_band_sk);
CREATE INDEX idx_p_start_date_sk ON tpcds.promotion (p_start_date_sk);
CREATE INDEX idx_p_end_date_sk ON tpcds.promotion (p_end_date_sk);
CREATE INDEX idx_p_item_sk ON tpcds.promotion (p_item_sk);
CREATE INDEX idx_customer_demographics_1 ON tpcds.customer_demographics (cd_marital_status, cd_education_status);
CREATE INDEX idx_customer_address_1 ON tpcds.customer_address (ca_state, ca_country);
CREATE INDEX idx_store_sales_1 ON tpcds.store_sales (ss_sales_price, ss_net_profit);
CREATE INDEX idx_store_sales_2 ON tpcds.store_sales (ss_quantity, ss_ext_sales_price, ss_net_profit);
CREATE INDEX idx_store_sales_quantity_1 ON tpcds.store_sales (ss_quantity);
CREATE INDEX idx_store_sales_quantity_2 ON tpcds.store_sales (ss_quantity, ss_list_price, ss_coupon_amt, ss_wholesale_cost);
CREATE INDEX idx_item_1 ON tpcds.item(i_category);
CREATE INDEX idx_item_2 ON tpcds.item(i_category, i_current_price);
