#!/bin/bash

set -e

PWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $PWD/../../functions.sh

GEN_DATA_SCALE=$1
session_id=$2
# $3 is leftover EXPLAIN_ANALYZE from the unified arg list; 07 never uses it.
EXCLUDE_HEAVY_QUERIES=$4
SQL_ON_ERROR_STOP=$5
DBNAME=$6
STATEMENT_TIMEOUT=$7
RUN_SQL_WITH_DUCKDB=$8
DUCKDB_MEMORY_LIMIT=$9
DUCKDB_THREADS=${10}
DUCKDB_MAX_WORKERS_PER_POSTGRES_SCAN=${11}
DUCKDB_THREADS_FOR_POSTGRES_SCAN=${12}
SKIP_QUERIES_LIST=${13}

if [[ "$GEN_DATA_SCALE" == "" || "$session_id" == "" ]]; then
	echo "Error: you must provide the scale and the session id as parameters."
	echo "Example: ./test.sh 3000 2"
	echo "This will execute the TPC-DS queries for 3TB of data for session 2."
	exit 1
fi
if [ -z "$STATEMENT_TIMEOUT" ]; then
	STATEMENT_TIMEOUT="1h"
fi
if [ -z "$RUN_SQL_WITH_DUCKDB" ]; then
	RUN_SQL_WITH_DUCKDB="false"
fi
if [ -z "$DUCKDB_MEMORY_LIMIT" ]; then
	DUCKDB_MEMORY_LIMIT="4GB"
fi
if [ -z "$DUCKDB_THREADS" ]; then
	DUCKDB_THREADS="-1"
fi
if [ -z "$DUCKDB_MAX_WORKERS_PER_POSTGRES_SCAN" ]; then
	DUCKDB_MAX_WORKERS_PER_POSTGRES_SCAN="2"
fi
if [ -z "$DUCKDB_THREADS_FOR_POSTGRES_SCAN" ]; then
	DUCKDB_THREADS_FOR_POSTGRES_SCAN="2"
fi
if [ -z "${SKIP_QUERIES_LIST+x}" ]; then
	SKIP_QUERIES_LIST=""
fi

source_bashrc
set_tpc_pgport_for_step "$PWD"
apply_tpc_pgport
validate_skip_queries_list "$SKIP_QUERIES_LIST"

step=testing_$session_id

init_log $step

if [ "$SQL_ON_ERROR_STOP" == "true" ]; then
        ON_ERROR_STOP=1
else
        ON_ERROR_STOP=0
fi

PSQL_SESSION_SETS="SET statement_timeout='$STATEMENT_TIMEOUT';"
if [ "$RUN_SQL_WITH_DUCKDB" == "true" ]; then
	PSQL_SESSION_SETS="$PSQL_SESSION_SETS SET duckdb.force_execution TO true;"
	PSQL_SESSION_SETS="$PSQL_SESSION_SETS SET duckdb.memory_limit TO '$DUCKDB_MEMORY_LIMIT';"
	PSQL_SESSION_SETS="$PSQL_SESSION_SETS SET duckdb.threads TO $DUCKDB_THREADS;"
	PSQL_SESSION_SETS="$PSQL_SESSION_SETS SET duckdb.max_workers_per_postgres_scan TO $DUCKDB_MAX_WORKERS_PER_POSTGRES_SCAN;"
	PSQL_SESSION_SETS="$PSQL_SESSION_SETS SET duckdb.threads_for_postgres_scan TO $DUCKDB_THREADS_FOR_POSTGRES_SCAN;"
fi


sql_dir=$PWD/$session_id
#going from 1 base to 0 base
tpcds_id=$((session_id-1))
tpcds_query_name="query_""$tpcds_id"".sql"
query_id=1
for p in $(seq 1 99); do
	q=$(printf %02d $query_id)
	template_filename=query$p.tpl
	start_position=""
	end_position=""
	for pos in $(grep -n $template_filename $sql_dir/$tpcds_query_name | awk -F ':' '{print $1}'); do
		if [ "$start_position" == "" ]; then
			start_position=$pos
		else
			end_position=$pos
		fi
	done

	#get the query number (the order of query execution) generated by dsqgen
	file_id=$(sed -n "$start_position","$start_position"p $sql_dir/$tpcds_query_name | awk -F ' ' '{print $4}')
	file_id=$(($file_id+100))
	filename=$file_id.query.$q.sql

	#add explain analyze 
	#echo "echo \":EXPLAIN_ANALYZE\" > $sql_dir/$filename"
	echo ":EXPLAIN_ANALYZE" > $sql_dir/$filename

	#echo "sed -n \"$start_position\",\"$end_position\"p $sql_dir/$tpcds_query_name >> $sql_dir/$filename"
	sed -n "$start_position","$end_position"p $sql_dir/$tpcds_query_name >> $sql_dir/$filename
	query_id=$(($query_id + 1))
	#echo "Completed: $sql_dir/$filename"
done
echo "rm -f $sql_dir/query_*.sql"
rm -f $sql_dir/$tpcds_query_name

echo ""
echo "queries 14, 23, 24, and 39 have 2 queries in each file.  Need to add :EXPLAIN_ANALYZE to second query in these files"
echo ""
arr=("*.query.14.sql" "*.query.23.sql" "*.query.24.sql" "*.query.39.sql")

for z in "${arr[@]}"; do
	echo $z
	myfilename=$sql_dir/$z
	echo "myfilename: $myfilename"
	pos=$(grep -n ";" $myfilename | awk -F ':' '{print $1}' | head -1)
	pos=$(($pos+1))
	echo "pos: $pos"
	sed -i ''$pos'i\'$'\n'':EXPLAIN_ANALYZE'$'\n' $myfilename
done

tuples="0"


for i in $(ls $sql_dir/*.sql); do
	id=$i
        qnum=`echo $i | awk -F '.' '{print $3}'`
	if should_skip_tpcds_query "$qnum"; then
		echo "Skipping $qnum due to SKIP_QUERIES_LIST=${SKIP_QUERIES_LIST}."
		continue
	fi
        if [ "$EXCLUDE_HEAVY_QUERIES" == "true" ]; then

                if [[
                "$qnum" == "02" ||
                "$qnum" == "04" ||
                "$qnum" == "05" ||
                "$qnum" == "09" ||
                "$qnum" == "10" ||
                "$qnum" == "11" ||
                "$qnum" == "14" ||
                "$qnum" == "16" ||
                "$qnum" == "17" ||
                "$qnum" == "18" ||
                "$qnum" == "22" ||
                "$qnum" == "23" ||
                "$qnum" == "24" ||
                "$qnum" == "25" ||
                "$qnum" == "28" ||
                "$qnum" == "29" ||
                "$qnum" == "31" ||
                "$qnum" == "35" ||
                "$qnum" == "36" ||
                "$qnum" == "38" ||
                "$qnum" == "39" ||
                "$qnum" == "44" ||
                "$qnum" == "46" ||
                "$qnum" == "47" ||
                "$qnum" == "50" ||
                "$qnum" == "51" ||
                "$qnum" == "57" ||
                "$qnum" == "59" ||
                "$qnum" == "64" ||
                "$qnum" == "65" ||
                "$qnum" == "67" ||
                "$qnum" == "70" ||
                "$qnum" == "72" ||
                "$qnum" == "74" ||
                "$qnum" == "75" ||
                "$qnum" == "76" ||
                "$qnum" == "78" ||
                "$qnum" == "79" ||
                "$qnum" == "80" ||
                "$qnum" == "82" ||
                "$qnum" == "87" ||
                "$qnum" == "88" ||
                "$qnum" == "93" ||
                "$qnum" == "94" ||
                "$qnum" == "95" ||
                "$qnum" == "96" ||
                "$qnum" == "97" ||
                "$qnum" == "99" ]]; then

                        echo "Skipping $i due to EXCLUDE_HEAVY_QUERIES=true."
                continue
                fi
	fi

	start_log
	schema_name=$session_id
	table_name=$(basename $i | awk -F '.' '{print $3}')
	sql_outfile=$(mktemp)
	sql_errfile=$(mktemp)
	hostfile=$(mktemp)
	psql_rc=0

	echo "psql -d $DBNAME -c \"$PSQL_SESSION_SETS\" -v ON_ERROR_STOP=$ON_ERROR_STOP -A -q -t -P pager=off -v EXPLAIN_ANALYZE=\"\" -f $i | wc -l"
	set +e
	psql_run_sql_capturing_host "$i" "$sql_outfile" "$sql_errfile" "$hostfile" ""
	psql_rc=$?
	set -e
	if [ -s "$sql_errfile" ]; then
		cat "$sql_errfile" >&2
	fi
	tuples=$(wc -l < "$sql_outfile" | tr -d ' ')
	# remove the extra line that \timing adds (legacy behaviour)
	if [ "$tuples" -gt 0 ]; then
		tuples=$((tuples - 1))
	fi

	QUERY_STATUS=$(sql_query_status "$sql_errfile" "$psql_rc")
	log $tuples
	unset QUERY_STATUS QUERY_BACKEND_HOST
	rm -f "$sql_outfile" "$sql_errfile" "$hostfile"
done

end_step $step
